### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by yihuan-github** [tencent-ailab/pika#11]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/speech/anaconda3/envs/pika/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/speech/anaconda3/envs/pika/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/speech/\udce6\udca1\udc8c\udce9\udc9d\udca2/pika/loader/otf_utt_loader.py", line 56, in put_thread
    for item in generator(*gen_args):
  File "/home/speech/\udce6\udca1\udc8c\udce9\udc9d\udca2/pika/loader/utt_loader.py", line 190, in utt_generator
    splice(feats, args.lctx, args.rctx)[::args.stride]
ValueError: could not broadcast input array from shape (143,78) into shape (143,240)

**Comment by csukuangfj** [comment]
Looks like your feat dim is not correct.
`26 * 3` vs `80 * 3`.
